### PR TITLE
Fix async issues

### PR DESCRIPTION
**Pull request by n-pochet**
Fixes issue #797

### CODE REVIEW

**Comment by quba42** [comment]
Just saw you re-pushed with new commit message, the CI will also want you to add the following file:
```
CHAGNES/797.bugfix
```
This file should contain a short description of the change, something like:
```
Fixed an async error preventing synchronization with ``sync_installer`` set to ``True``.
```
This will be used for the changelog, once this PR is released.

**Comment by n-pochet** [comment]
@quba42 Thanks for the heads-up!

**Comment by quba42** [comment]
Ok, so the CI wants:
```
closes #797
```
or else
```
fixes #797
```
instead of
```
closes pulp#797
```
It is a fussy CI, but one gets used to it. :wink:

**Comment by n-pochet** [comment]
Thanks @quba42!
That's what I figured out after looking at the raw commit messages instead of the ones on Github.
Thank you for the clarification

**Comment by hstct** [comment]
> ```
> closes pulp#797
> ```

Seems to work as well. At least CI is not complaining :)

**Comment by quba42** [comment]
@n-pochet I will try to test/merge/release this ASAP. But I don't think we have the time to do a release this week anyway, so hopefully next week.

**Comment by n-pochet** [comment]
@quba42 Thanks for the feedback.
Do not hesitate to ping me if I can be of any help!

**Comment by n-pochet** [comment]
@quba42 Can I do anything to help?

**Review by hstct — APPROVED** [review]
Tested it locally and it fixes the issue.

LGTM

**Review by mdellweg — APPROVED** [review]
LGTM

**Pull request merged**
