### PR TITLE
1.10.1 cps

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by quba42** [comment]
If you could also cherry-pick c5c0647d4a3f4954345809ef30e193f15f046e52 that would be good.
(That commit isn't associated with any issue...)

Note: With the addition of this commit the only difference between `1.10-release` and `master` would be that `master` contains some more tests.
Question: What would need to happen to create an `1.11-release` branch at the current tip of master instead of this merge?

**Comment by quba42** [comment]
Were we meant to have merged this (https://github.com/pulp/pulp_deb/pull/98) at some point?
P.S: Please excuse my great ignorance regarding the pulp2 release process...

**Comment by evgeni** [comment]
@ipanova is @quba42's request reasonable? the code looks so, but I don't know if you need anything in terms of bookkeeping/release notes.

**Comment by ipanova** [comment]
Sounds good, lets pick that one as well.Release notes are usually kept by
plugins, I think debian doesn't have those, or at least I have not find any.

**Comment by evgeni** [comment]
Cool. Picked!

**Pull request merged**
