### PR TITLE
Fix docs due to renaming of pulpcore-content-app to pulpcore-content

### PR DESCRIPTION
**Pull request by goosemania**
[noissue]

### CODE REVIEW

**Comment by mdellweg** [comment]
Approved the change. But a changelog entry seems to me missing.

**Comment by goosemania** [comment]
Oh, I didn't realise that you've released the other docs change for the same issue. Ok, I'll add a changelog entry.

**Comment by mdellweg** [comment]
Ahh, that's the problem. Then a [noissue] should be good enough, but you must amend the commit with it.

**Comment by mdellweg** [comment]
Thank you!

**Pull request merged**
