### PR TITLE
Update CI files

### PR DESCRIPTION
**Pull request by pulpbot**
[noissue]

### CODE REVIEW

**Comment by mdellweg** [comment]
Looks like the signingservice did not get setup in the azure test. I wonder why.

**Comment by quba42** [comment]
It needs a proper test setup, I know...

**Comment by mdellweg** [comment]
But it worked with s3. What is the difference in the setup here?

**Comment by quba42** [comment]
Maybe s3 is set up to run the post before (or whatever they are called) tests, and azure is not?

**Pull request closed without merging**
