### PR TITLE
Read package indices from different compression algorithms

### PR DESCRIPTION
**Pull request by mdellweg**

### CODE REVIEW

**Comment by bmbouter** [comment]
I tried this PR out with the following commands and I got an error.

```
export REPOSITORY=$(http POST :24817/pulp/api/v3/repositories/ name=debian_stretch | jq -r '._href')
export REMOTE=$(http POST :24817/pulp/api/v3/remotes/deb/apt/ name=debian_stretch policy=streamed url="http://ftp.de.debian.org/debian/" distributions=stretch components=main architectures=amd64 sync_udebs=True sync_installer=True | jq -r '._href')
export SYNC_TASK=$(http POST :24817${REMOTE}sync/ repository=${REPOSITORY} | jq -r '.task'
```

The task fails and it says:

```
May 16 17:52:52 pulp3-source-fedora29.localhost.example.com rq[30924]:     rv = job.perform()
May 16 17:52:52 pulp3-source-fedora29.localhost.example.com rq[30924]:   File "/usr/local/lib/pulp/lib64/python3.7/site-packages/rq/job.py", line 588, in perform
May 16 17:52:52 pulp3-source-fedora29.localhost.example.com rq[30924]:     self._result = self._execute()
May 16 17:52:52 pulp3-source-fedora29.localhost.example.com rq[30924]:   File "/usr/local/lib/pulp/lib64/python3.7/site-packages/rq/job.py", line 594, in _execute
May 16 17:52:52 pulp3-source-fedora29.localhost.example.com rq[30924]:     return self.func(*self.args, **self.kwargs)
May 16 17:52:52 pulp3-source-fedora29.localhost.example.com rq[30924]:   File "/home/vagrant/devel/pulp_deb/pulp_deb/app/tasks/synchronizing.py", line 88, in synchronize
May 16 17:52:52 pulp3-source-fedora29.localhost.example.com rq[30924]:     mirror=mirror,
May 16 17:52:52 pulp3-source-fedora29.localhost.example.com rq[30924]:   File "/home/vagrant/devel/pulpcore-plugin/pulpcore/plugin/stages/declarative_version.py", line 169, in create
May 16 17:52:52 pulp3-source-fedora29.localhost.example.com rq[30924]:     loop.run_until_complete(pipeline)
May 16 17:52:52 pulp3-source-fedora29.localhost.example.com rq[30924]:   File "/usr/lib64/python3.7/asyncio/base_events.py", line 568, in run_until_complete
May 16 17:52:52 pulp3-source-fedora29.localhost.example.com rq[30924]:     return future.result()
May 16 17:52:52 pulp3-source-fedora29.localhost.example.com rq[30924]:   File "/home/vagrant/devel/pulpcore-plugin/pulpcore/plugin/stages/api.py", line 209, in create_pipeline
May 16 17:52:52 pulp3-source-fedora29.localhost.example.com rq[30924]:     await asyncio.gather(*futures)
May 16 17:52:52 pulp3-source-fedora29.localhost.example.com rq[30924]:   File "/home/vagrant/devel/pulpcore-plugin/pulpcore/plugin/stages/api.py", line 43, in __call__
May 16 17:52:52 pulp3-source-fedora29.localhost.example.com rq[30924]:     await self.run()
May 16 17:52:52 pulp3-source-fedora29.localhost.example.com rq[30924]:   File "/home/vagrant/devel/pulp_deb/pulp_deb/app/tasks/synchronizing.py", line 227, in run
May 16 17:52:52 pulp3-source-fedora29.localhost.example.com rq[30924]:     filename = _uncompress_artifact(d_content.d_artifacts)
May 16 17:52:52 pulp3-source-fedora29.localhost.example.com rq[30924]:   File "/home/vagrant/devel/pulp_deb/pulp_deb/app/tasks/synchronizing.py", line 261, in _uncompress_artifact
May 16 17:52:52 pulp3-source-fedora29.localhost.example.com rq[30924]:     raise NoPackageIndexFile()
May 16 17:52:52 pulp3-source-fedora29.localhost.example.com rq[30924]: pulp_deb.app.tasks.synchronizing.NoPackageIndexFile
```

**Comment by bmbouter** [comment]
@mdellweg would it be possible to put the script you test with in the README?

**Comment by bmbouter** [comment]
This uses two Publication types, very cool.

**Comment by bmbouter** [comment]
The sync worked! I ran into an issue when I went to make a Publication though. Here's my script:

```
# Sync Repository
export REPOSITORY=$(http POST :24817/pulp/api/v3/repositories/ name=debian_stretch | jq -r '._href')
export REMOTE=$(http POST :24817/pulp/api/v3/remotes/deb/apt/ name=debian_stretch policy=streamed url="http://ftp.de.debian.org/debian/" distributions=stretch components=main architectures=amd64 sync_udebs=True sync_installer=True | jq -r '._href')
export SYNC_TASK=$(http POST :24817${REMOTE}sync/ repository=${REPOSITORY} | jq -r '.task')
# wait for task to finish

# Create a Publication for 'repository'
http POST :24817/pulp/api/v3/publications/deb/verbatim/ repository=$REPOSITORY
```

I get this exception, maybe it needs migraiton 0001 to be regenerated? We're recommending all plugins continue to remake migration 0001 until our GA date. It's a strange thing to do but we tell all users there is no RC -> RC upgrade paths so it's safe.

**Comment by mdellweg** [comment]
@bmbouter You just need to remove you local migrations, as they are still not checked in at all.

**Comment by bmbouter** [comment]
@mdellweg great I'll try this again soon!

**Comment by bmbouter** [comment]
It doesnt' seem like a blocker, but during sync I see errors like this:

```
May 17 19:48:58 pulp3-source-fedora29.localhost.example.com rq[27852]: pulp: backoff:ERROR: Giving up _run(...) after 1 tries (aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found')
May 17 19:48:58 pulp3-source-fedora29.localhost.example.com rq[27852]: pulp: pulp_deb.app.tasks.synchronizing:INFO: Artifact not found. Ignored
May 17 19:48:59 pulp3-source-fedora29.localhost.example.com rq[27852]: Giving up _run(...) after 1 tries (aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found')
```

Do you know why pulp_deb is requesting content that 404s?

**Comment by bmbouter** [comment]
On a fedora28 Pulp machine (which isn't affected by the yarl bug) the VM boots fully and successfully! With this working environment I'm going to record a demo. @mdellweg will you merge or should I?

**Comment by mdellweg** [comment]
@bmbouter thanks for the extensive review

**Comment by mdellweg** [comment]
> Do you know why pulp_deb is requesting content that 404s?

Yes. Sometimes, the Packages file is only available in compressed form, which is ok, if you can download it in at least one form. We try all versions and ignore 404 as long as there is at least one success. This is, what the `DeclarativeFailsafeArtifact` is for.

**Comment by bmbouter** [comment]
Thanks for the info!

**Pull request merged**
