### PR TITLE
Check `done` instead of `total` in sync test

### PR DESCRIPTION
**Pull request by mdellweg**
[noissue]

### CODE REVIEW

**Comment by hstct** [comment]
Not sure why the amount of the content change again 😕

**Comment by mdellweg** [comment]
Seems like the artifact count can differ. Would it be ok to only check the content count?

**Comment by quba42** [comment]
I guess the idea is to assert that certain orphans were removed by the orphan cleanup. Maybe there is a more direct way to assert this. (Like record the actual artifact href that we think is an orphan and then assert that it no longer exists). This would avoid "counts" altogether.

**Comment by mdellweg** [comment]
> I guess the idea is to assert that certain orphans were removed by the orphan cleanup. Maybe there is a more direct way to assert this. (Like record the actual artifact href that we think is an orphan and then assert that it no longer exists). This would avoid "counts" altogether.

My thinking is, we know about the content we expect to be removed. Let pulpcore handle the artifacts...
But we can also issue a list of hrefs to orphan cleanup. And if we requested 2 items to remove and the done is 2 that would be very precise. I'd rather not do that in this PR...

**Review by hstct — APPROVED** [review]

**Pull request merged**
