### PR TITLE
Bindings installation on dev environment

### PR DESCRIPTION
**Pull request by fabricio-aguiar**
https://pulp.plan.io/issues/6221
ref #6221

### CODE REVIEW

**Comment by fabricio-aguiar** [comment]
> I guess this is this coming from plugin_template?

it did not come from plugin_template, I just thought it would be nice to have this doc matching with pulpcore: https://github.com/pulp/pulpcore/pull/598

**Comment by mdellweg** [comment]
So should it be in plugin_template, too?

**Comment by mdellweg** [comment]
Thank you @fabricio-aguiar !

**Comment by fabricio-aguiar** [comment]
> So should it be in plugin_template, too?

good point! I think it could be valuable

**Pull request merged**
