### PR TITLE
Add touch statements to prevent false positives during orphan cleanup

### PR DESCRIPTION
**Pull request by quba42**
Closes #9162
https://pulp.plan.io/issues/9162

### CODE REVIEW

**Comment by quba42** [comment]
I am very unsure if the two identified touch statements are needed, and also unsure if I need extra touch statements...

**Comment by mdellweg** [comment]
This patch should be accompanied with a version bump to pulpcore>=3.14.
Alternatively you can only call "touch" if `has_attr`.

**Comment by quba42** [comment]
Some more references:

- https://github.com/pulp/community/discussions/59
- https://github.com/pulp/community/discussions/58

**Review by mdellweg — APPROVED** [review]
I didn't look for cases...

**Comment by quba42** [comment]
@mdellweg, @daviddavis suggested [this](https://github.com/pulp/pulp_deb/blob/33c878e640bd232b8684bc84e0b0df49b405243b/pulp_deb/app/serializers/content_serializers.py#L74-L82) might be a candidate, but I don't see it. Looks to me like that artifact is only retrieved to then throw the error (so does not need cleanup protection?). Could you have one more look at that example if I am getting this right or wrong?

**Comment by daviddavis** [comment]
Adding a touch call to `deferred_validate` is not essential but it would prevent the content from being cleaned up before the user has a chance to use it (ie add it to a repo version).

**Comment by mdellweg** [comment]
It's hard to tell. Look to me like the user wanted to create such a thing if he received that answer, so maybe touch is a good idea.

**Comment by quba42** [comment]
I added three more touch calls. I also added comments on what the intention behind each call is.
Unless there is more feedback, I will merge this version, and backport it to the 2.14 branch. (Gives me a chance to try out cherry-pick automation.)

**Pull request merged**
