### PR TITLE
Update versions for 1.7.0 alpha

### PR DESCRIPTION
**Pull request by pcreech**
Update versions for 1.7.0 alpha

### CODE REVIEW

**Comment by dralley** [comment]
Testrunner complains about PEP8 issues, but not related to this PR

```
./plugins/pulp_deb/plugins/importers/sync.py:126:5: E301 expected 1 blank line, found 0
./plugins/pulp_deb/plugins/importers/sync.py:171:5: E301 expected 1 blank line, found 0
./plugins/pulp_deb/plugins/importers/sync.py:198:5: E301 expected 1 blank line, found 0
./plugins/pulp_deb/plugins/importers/sync.py:226:5: E301 expected 1 blank line, found 0
./plugins/pulp_deb/plugins/importers/sync.py:247:5: E301 expected 1 blank line, found 0
```

**Comment by pcreech** [comment]
I'm proposing to ignore the pep8 issues here, as this is automated code changes from long standing releng tooling

**Comment by pcreech** [comment]
@mibanescu Looking at the diff here, it looks like you have different components versioned differently.  Can you provide guidance on what these versions are supposed to be?

**Comment by mibanescu** [comment]
To quote Car Talk: the versioning scheme is "unencumbered by the thought process". There are too many of them, spread over too many files, and some/most don't make any sense to me. I mostly care about the one in the spec file, because that's how I build the rpm, and possibly the one under setup.py. If you want to make them all consistent with how other plugins work, please do so.

**Comment by pcreech** [comment]
@mibanescu cool, thanks!  Merging

**Pull request merged**
