### PR TITLE
Update CI files

### PR DESCRIPTION
**Pull request by pulpbot**
[noissue]

### CODE REVIEW

**Review by mdellweg — APPROVED** [review]

**Comment by quba42** [comment]
@mdellweg Do you know what happens if I don't merge this by the next time the "CI Update" workflow runs?

**Comment by mdellweg** [comment]
It should keep updating this PR.
It's worth a try, eh?

**Comment by mdellweg** [comment]
This one doesn't seem to change anything. So maybe it is just about the right one for an experiment.

**Comment by mdellweg** [comment]
With the new change, it may be necessary to adjust the "required checks" after merging this.

**Comment by quba42** [comment]
> With the new change, it may be necessary to adjust the "required checks" after merging this.

What do you mean by "required checks"?

**Comment by mdellweg** [comment]
I mean the fact that they are marked as required for a PR to be merged, but nevermind, it looks like github does that by filename and not workflow name.
image

**Pull request merged**
