### PR TITLE
Update for Pulp 2.8

### PR DESCRIPTION
**Pull request by sjtindell**
Made basic modifications to get the plugin functioning with Pulp 2.8. Will require significant cleanup in future but for now plugin can sync from remote/local and publish over http.

### CODE REVIEW

**Comment by seandst** [comment]
ok test

**Comment by seandst** [comment]
The jenkins logs are sadly not public, but jenkins is showing failures and errors on all platforms.

**Comment by sjtindell** [comment]
Okay, I am new to pull requests. The plugin is non-functional without my changes. I will just work on my fork in future.

**Comment by seandst** [comment]
Well, if the tests are failing there's a decent chance that the plugin is malfunctional, which might not be an improvement over nonfunctional. The `run-tests.py` script at the root of the project should report any linting issues and test failures.

**Comment by mmoll** [comment]
@aschieb could you also have a look here?

**Comment by sjtindell** [comment]
Sorry to take your time, when I get it to a more acceptable state I will re-submit.

**Comment by mmoll** [comment]
@sjtindell it's probably still interesting for other people working on it, to take as a base.

**Pull request closed without merging**
