### PR TITLE
Basic implementation

### PR DESCRIPTION
**Pull request by mdellweg**
~~OK, far from ready, but~~ this way, we can start discussing...

### CODE REVIEW

**Comment by dralley** [comment]
"Watch" the plugin-template repo so that as tests get added and updated you can get notifications

**Comment by mdellweg** [comment]
I think, this is now in a rather good state. Any objections to merging it into 3-master?

**Comment by mibanescu** [comment]
No time to review it, but I have no objection.

**Comment by dralley** [comment]
I gave it a brief look over and didn't notice anything amiss.

**Comment by mdellweg** [comment]
Thank you all! I consider this a milestone.

**Pull request merged**
