### PR TITLE
Update standard test data repo to include source package files

### PR DESCRIPTION
**Pull request by hstct**
[noissue]

### CODE REVIEW

**Comment by hstct** [comment]
Let's see if this works with locally built data. :crossed_fingers:

**Comment by masselstine** [comment]
@hstct is this expected to include mimir_1.0.tar.xz? I am just rebasing my source work on this commit and the .dsc references mimir_1.0.tar.xz but this of course fails when the test sync is attempted.

**Comment by hstct** [comment]
@masselstine huh, yes you are right. I'm not sure why it didn't add it. I will fix it once I'm back at the computer. Good find thanks!

**Comment by hstct** [comment]
Hm somehow my system had a global gitignore on `.tar.*` files. Should be good now!

**Comment by masselstine** [comment]
> Hm somehow my system had a global gitignore on `.tar.*` files. Should be good now!

No worries. I am about to give it another try with my stuff later today or tomorrow. I will let you know if I hit any other issues. Thanks for getting this in place.

**Comment by masselstine** [comment]
> > Hm somehow my system had a global gitignore on `.tar.*` files. Should be good now!
> 
> No worries. I am about to give it another try with my stuff later today or tomorrow. I will let you know if I hit any other issues. Thanks for getting this in place.

Woohoo! I fetched your updated change from https://github.com/ATIX-AG/pulp_deb.git add-source-package-test-data and updated the assertion data and all is well. Thanks for making the update. Once this is merged I will get my PR updated.

**Review by quba42 — APPROVED** [review]

**Pull request merged**
