### PR TITLE
Rename the master branch to main

### PR DESCRIPTION
**Pull request by quba42**
[noissue]

With this change, I will need to push a new branch `main`, change the repositories default branch to it, add the branch protection rule, and finally delete the `master` branch.

- [x] Add `main` branch to the repo.
- [x] Add branch protection for the `main` branch.
- [ ] Merge this PR to the new `main` branch.
- [ ] Make the `main` branch the default branch.
- [ ] Unprotect and delete the `master` branch.

### CODE REVIEW

**Comment by quba42** [comment]
There are currently still five hits for `git grep master`. Three of them refer to the pulpcore master, one refers to the pulp-fixtures master, and one is part of a sphinx variable. These will need to remain for now.

**Comment by mdellweg** [comment]
Have you considered calling it "develop" ?

**Comment by quba42** [comment]
> Have you considered calling it "develop" ?

I guess my thinking was that in the past the presence of a "develop" branch has implied a specific workflow involving both a "develop" and a "master" branch. But if other projects are now using "develop" _instead_ of "master", I am fine with going along with that for consistency. If I have noticed correctly the [foreman-ansible-modules](https://github.com/theforeman/foreman-ansible-modules) appear to have gone this route.

**Comment by ipanova** [comment]
> > Have you considered calling it "develop" ?
> 
> I guess my thinking was that in the past the presence of a "develop" branch has implied a specific workflow involving both a "develop" and a "master" branch. But if other projects are now using "develop" _instead_ of "master", I am fine with going along with that for consistency. If I have noticed correctly the [foreman-ansible-modules](https://github.com/theforeman/foreman-ansible-modules) appear to have gone this route.
I have looked in the internet a bit and usually people go whether with main or develop. I think this is matter of preference in the end of the day and you should call the shots :tropical_drink:

**Comment by quba42** [comment]
> I have looked in the internet a bit and usually people go whether with main or develop. I think this is matter of preference in the end of the day and you should call the shots tropical_drink

I guess I prefer "main". Statements like: "When working with Git repositories everyone wants to merge there changes into the main branch" or "PRs are opened against the main branch" just make the most sense to me with "main". I also like consistency, so if I ever find the rest of the project has all moved to "devel", I may revise my personal policy. :stuck_out_tongue_winking_eye:

**Pull request merged**
