### PR TITLE
Update pulp-fixtures port

### PR DESCRIPTION
**Pull request by daviddavis**
[noissue]

### CODE REVIEW

**Comment by quba42** [comment]
I am guessing I will want to cherry-pick this to any release branches that still need to run tests (once the new port goes live)?

**Comment by daviddavis** [comment]
> I am guessing I will want to cherry-pick this to any release branches that still need to run tests (once the new port goes live)?

Yes, correct.

**Comment by daviddavis** [comment]
The new port is live already by the way.

**Review by quba42 — APPROVED** [review]
This can be merged at any time, however right now the pulp_deb tests are broken anyway due to changes to SigningService in pulpcore.
I will probably merge this once I get around to fixing those.

**Comment by quba42** [comment]
Closing, since this change was applied via the plugin template by https://github.com/pulp/pulp_deb/pull/251.

**Pull request closed without merging**
